name: The Alchemical Mirror of Sophia
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50491
title: The Alchemical Mirror of Sophia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c0e4fa'
    - '#fbfcfe'
    - '#8cbbed'
    - '#8480df'
    - '#b9a3e1'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
