name: The Alchemical Mirror of Sophia
favicon: null
layout_spectrum: 0.7527243874501437
typography_spectrum: 0.7274782666936517
title: The Alchemical Mirror of Sophia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
